export const ENV_KEYS = {
  PORT: 'PORT',
  JWT_SECRET: 'JWT_SECRET',
  DATABASE_URL: 'DATABASE_URL',

  //storage providers
  CLOUDINARY_API_KEY: 'CLOUDINARY_API_KEY',
  IMAGEKIT_PRIVATE_KEY: 'IMAGEKIT_PRIVATE_KEY',
  FILE_STORAGE_PROVIDER: 'FILE_STORAGE_PROVIDER',
  CLOUDINARY_CLOUD_NAME: 'CLOUDINARY_CLOUD_NAME',
  CLOUDINARY_API_SECRET: 'CLOUDINARY_API_SECRET',
  FILE_STORAGE_ROOT_FOLDER: 'FILE_STORAGE_ROOT_FOLDER',
} as const;

export const ENV_DEFAULTS = {
  PORT: 3000,
  FILE_STORAGE_ROOT_FOLDER: 'marketplace-core',
} as const;
